"""Add SprintSession table

Revision ID: f91865c9b85e
Revises: f2a6b2dbee49
Create Date: 2026-04-05 22:58:29.965482
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f91865c9b85e'
down_revision: Union[str, None] = 'f2a6b2dbee49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprint_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sprint_type', sa.Enum('COMPARISON', 'STANDARD', name='sprinttype'), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprint_sessions_user_id'), 'sprint_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sprint_sessions_user_id'), table_name='sprint_sessions')
    op.drop_table('sprint_sessions')
    # ### end Alembic commands ###
